prueba:
    resource: "@pruebaBundle/Resources/config/routing.yml"
    prefix:   /

hola:
    resource: "@HolaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
