content_content_homepage:
    path:     /
    defaults: { _controller: ContentContentBundle:Default:index }

content_content_cuidador:
    path:     /cuidador/{idCuidador}
    defaults: { _controller: ContentContentBundle:Default:getCuidadorData }
